
SRCS =	test.cpp					\
		src/IRCParserBot.cpp		\
		../src/IRCParser.cpp		\
		../src/IRCParser_parse.cpp	\
		../src/IRCException.cpp

all:
	g++ -D__BOT -std=c++2a -Wall -Wextra ${SRCS} -I../inc -o test
